export const LIST_QUESTIONS_REQUEST = 'LIST_QUESTIONS_REQUEST'
export const LIST_QUESTIONS_SUCCESS = 'LIST_QUESTIONS_SUCCES'
export const LIST_QUESTIONS_FAIL = 'LIST_QUESTIONS_FAIL'

export const CREATE_QUESTIONS_REQUEST = 'CREATE_QUESTIONS_REQUEST'
export const CREATE_QUESTIONS_SUCCESS = 'CREATE_QUESTIONS_SUCCES'
export const CREATE_QUESTIONS_FAIL = 'CREATE_QUESTIONS_FAIL'
export const CREATE_QUESTIONS_RESET = 'CREATE_QUESTIONS_RESET'

export const RESULT_QUESTIONS_REQUEST = 'RESULT_QUESTIONS_REQUEST'
export const RESULT_QUESTIONS_SUCCESS = 'RESULT_QUESTIONS_SUCCES'
export const RESULT_QUESTIONS_FAIL = 'RESULT_QUESTIONS_FAIL'

export const LISTADMIN_QUESTIONS_REQUEST = 'LISTADMIN_QUESTIONS_REQUEST'
export const LISTADMIN_QUESTIONS_SUCCESS = 'LISTADMIN_QUESTIONS_SUCCES'
export const LISTADMIN_QUESTIONS_FAIL = 'LISTADMIN_QUESTIONS_FAIL'

export const UPDATE_QUESTIONS_REQUEST = 'UPDATE_QUESTIONS_REQUEST'
export const UPDATE_QUESTIONS_SUCCESS = 'UPDATE_QUESTIONS_SUCCES'
export const UPDATE_QUESTIONS_FAIL = 'UPDATE_QUESTIONS_FAIL'

export const DELETE_QUESTIONS_REQUEST = 'DELETE_QUESTIONS_REQUEST'
export const DELETE_QUESTIONS_SUCCESS = 'DELETE_QUESTIONS_SUCCES'
export const DELETE_QUESTIONS_FAIL = 'DELETE_QUESTIONS_FAIL'